/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chat_NcursesDisplay */

#ifndef _Included_chat_NcursesDisplay
#define _Included_chat_NcursesDisplay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chat_NcursesDisplay
 * Method:    initscr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_chat_NcursesDisplay_initscr
  (JNIEnv *, jobject);

/*
 * Class:     chat_NcursesDisplay
 * Method:    endwin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_chat_NcursesDisplay_endwin
  (JNIEnv *, jobject);

/*
 * Class:     chat_NcursesDisplay
 * Method:    mvprintw
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_chat_NcursesDisplay_mvprintw
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     chat_NcursesDisplay
 * Method:    getscr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_chat_NcursesDisplay_getscr
  (JNIEnv *, jobject);

/*
 * Class:     chat_NcursesDisplay
 * Method:    getch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_chat_NcursesDisplay_getch
  (JNIEnv *, jobject);

/*
 * Class:     chat_NcursesDisplay
 * Method:    getmaxy
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_chat_NcursesDisplay_getmaxy
  (JNIEnv *, jobject, jint);

/*
 * Class:     chat_NcursesDisplay
 * Method:    getmaxx
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_chat_NcursesDisplay_getmaxx
  (JNIEnv *, jobject, jint);

/*
 * Class:     chat_NcursesDisplay
 * Method:    exit_curses
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_chat_NcursesDisplay_exit_1curses
  (JNIEnv *, jobject, jint);

/*
 * Class:     chat_NcursesDisplay
 * Method:    wrefresh
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_chat_NcursesDisplay_wrefresh
  (JNIEnv *, jobject, jint);

/*
 * Class:     chat_NcursesDisplay
 * Method:    wclear
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_chat_NcursesDisplay_wclear
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
